name: awesome

on:
  schedule:
    - cron: "0 0 1 * *"
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install OpenAPI Generator
        run: npm i @openapitools/openapi-generator-cli -g

      - name: Generate Read API
        run: openapi-generator-cli generate -g rust -i https://www.thebluealliance.com/swagger/api_v3.json -o generated/read-api

      - name: Generate Write API
        run: openapi-generator-cli generate -g rust -i https://www.thebluealliance.com/swagger/api_trusted_v1.json -o generated/write-api

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add generated/read-api
          git add generated/write-api
          git commit -m "Generated Rust client library"
          git push
